variable "BCER-CP" {}
variable "EACL" {}
variable "EACL_STG" {}
variable "FMDB" {}
variable "GIS" {}
variable "HAMIS" {}
variable "HCIMWEB_HIAT1" {}
variable "HCIMWEB_HIAT2" {}
variable "HCIMWEB_HIAT3" {}
variable "HCIMWEB_HS1" {}
variable "HCIMWEB_HUAT" {}
variable "HEM" {}
variable "MIWT" {}
variable "MIWT_STG" {}
variable "MSPDIRECT-SERVICE" {}
variable "MSPDIRECT-SERVICE-UAT" {}
variable "SFDS" {}
variable "SWT" {}
variable "SWT_STG" {}
variable "TAP" {}